name: fastgr
dependencies:
- cycler=0.10.0=py27_0
- freetype=2.5.5=0
- libpng=1.6.17=0
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.1=0
- numpy=1.11.0=py27_0
- openssl=1.0.2g=0
- pip=8.1.1=py27_1
- pyparsing=2.1.1=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.5.2=py27_0
- pytz=2016.3=py27_0
- qt=4.8.7=1
- readline=6.2=2
- setuptools=20.7.0=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0

